Traceback (most recent call last):   File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 3080, in fromarray     mode, rawmode = _fromarray_typemap[typekey] KeyError: ((1, 1, 12), '|u1')
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/AttnGAN/code/main.py", line 146, in <module>
    gen_example(dataset.wordtoix, algo)  # generate images for customized captions
  File "/content/AttnGAN/code/main.py", line 83, in gen_example
    algo.gen_example(data_dic)
  File "/content/AttnGAN/code/trainer.py", line 510, in gen_example
    build_super_images2(im[j].unsqueeze(0),
  File "/content/AttnGAN/code/miscc/utils.py", line 243, in build_super_images2
    PIL_att = Image.fromarray(np.uint8(one_map))
  File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 3083, in fromarray
    raise TypeError(msg) from e
TypeError: Cannot handle this data type: (1, 1, 12), |u1